SURVEY_NAME: "HSC"
HSC:
  STAMP_PIXEL_SIZE: 45
  GALSIM_COSMOS_DATA_DIR: "../data/galsim_cosmos_data"
  CATALOG_NAMES: [
    "real_galaxy_catalog_26_extension_example.fits",
    "real_galaxy_catalog_26_extension_example_fits.fits",
  ]
  REAL_DATA_DIR: "../data/real_hsc_data"
  AVAILABLE_COADDS: [
    "9813_4,3",
    "9813_4,4",
  ]
