SURVEY_NAME: "HSC"
HSC:
  STAMP_PIXEL_SIZE: 45
  CATALOG_PATH: [
    "../data/catalogs/real_galaxy_catalog_26_extension_example.fits",
    "../data/catalogs/real_galaxy_catalog_26_extension_example_fits.fits",
]
  ISOLATED_GAL_DIR: "../data/hsc_isolated_images"
  PSF_DIR: "../data/hsc_psfs"
