SURVEY_NAME: "HSC"
HSC:
  STAMP_PIXEL_SIZE: 45
  CATALOG_PATH: [
    "../data/galsim_cosmos_data/real_galaxy_catalog_26_extension_example.fits",
    "../data/galsim_cosmos_data/real_galaxy_catalog_26_extension_example_fits.fits",
    ]
  AVAILABLE_COADDS: [
    "9813_4,3",
    "9813_4,4",
  ]
